const connection = require("../../../DB/db_config");
//Champs inserted successfully
var sqlQuery = `INSERT INTO Doctorant ( 
        Id_Doctorant,
        nom,
        prenom ,
        Date_naissance,
        sexe,
        mail,
        telephone,
        TypeDoctorat,
        Etablissement_origine_Master,
        Etablissement_origine_ingeniorat,
        Etablissement_origine_Magistere,
        Specialite,
        intitule_sujet,
        intitule_sujet_bis,
        PV_changement_these,
        Premiere_inscription,
        Nombre_inscriptions,
        Date_fichier_central,
        Id_Encadreur,
        Id_CoEncadreur,
        laboratoire,
        statut,
        date_derniere_reinscription,
        soutenu,
        date_soutenance,
        radie,
        abandon
    )
    VALUES ?`;

var values = [
  [
    "21/0021",
    "Louni",
    "Imène",
    "2004-04-04",
    "F",
    "li_louni@esi.dz",
    "0662601368",
    "Classique",
    null,
    "ESI",
    null,
    "SID",
    "Quantum comuting",
    null,
    null,
    "2020-03-13",
    3,
    "2019-02-02",
    null,
    null,
    "Fab Lab",
    "reinscrit",
    "2017-01-01 ",
    null,
    null,
    null,
    null,
  ],

  [
    "21/0022",
    "Allouche",
    "Imène",
    "2003-08-24",
    "F",
    "li_allouche@esi.dz",
    "0699240858",
    "Classique",
    null,
    "ESI",
    null,
    "SIQ",
    "Binary exploitation",
    null,
    null,
    "2020-03-13",
    3,
    "2019-02-02",
    null,
    null,
    "Fab Lab",
    "reinscrit",
    "2017-01-01 ",
    null,
    null,
    null,
    null,
  ],

  [
    "21/0010",
    "Attia",
    "Oussama Abderraouf",
    "2002-10-03",
    "H",
    "lo_attia@esi.dz",
    "0662601368",
    "Classique",
    null,
    "ESI",
    null,
    "SID",
    "Deep learning",
    null,
    null,
    "2020-03-13",
    3,
    "2019-02-02",
    null,
    null,
    "Fab Lab",
    "reinscrit",
    "2017-01-01 ",
    null,
    null,
    null,
    null,
  ],

  [
    "21/0009",
    "Derbal",
    "Rayhane",
    "2003-04-04",
    "F",
    "lr_derbal@esi.dz",
    "0662601368",
    "Classique",
    null,
    "ESI",
    null,
    "SID",
    "Quantum comuting",
    null,
    null,
    "2020-03-13",
    3,
    "2019-02-02",
    null,
    null,
    "Fab Lab",
    "reinscrit",
    "2017-01-01 ",
    null,
    null,
    null,
    null,
  ],

  [
    "21/0007",
    "Djafercherif",
    "Soumeya",
    "2002-04-04",
    "F",
    "ks_djafercherif@esi.dz",
    "0662601368",
    "Classique",
    null,
    "ESI",
    null,
    "SIL",
    "Big Data",
    null,
    null,
    "2020-03-13",
    3,
    "2019-02-02",
    null,
    null,
    "Fab Lab",
    "reinscrit",
    "2017-01-01 ",
    null,
    null,
    null,
    null,
  ],
];

connection.query(sqlQuery, [values]);
